# Generated by Django 2.0.2 on 2019-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xzy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='douban',
            name='num',
            field=models.CharField(max_length=100),
        ),
    ]
